### PR TITLE
Fix VisualStudioCode Snipped Code & Ignore `code-workspace`

### PR DESCRIPTION
**Pull request by kalaschnik**
The line `!.vscode/*.code-snippets` was not even shown in the API:
https://www.toptal.com/developers/gitignore/api/visualstudiocode

### CODE REVIEW

**Review by yusufzmly — APPROVED** [review]

**Comment by yusufzmly** [comment]
Thank you for taking the time to contribute, @kalaschnik

**Comment by janosroden** [comment]
Hi @kalaschnik and @yusufzmly, may I ask why it's so evident to ignore code-workspace files? It's like ignore *.sln or csproj files in a C# - Visual Studio project.
Similarly why want to ignore code snippets? 

I don't understand any piece of this PR.

**Comment by konstrybakov** [comment]
Hey, @janosroden, thank you for pointing this out 👍! 

After some investigation, I am sure we should revert the changes implemented in this PR. I believe, and also according to the docs and the official `.gitignore` template from `github` [here](https://github.com/github/gitignore/blob/main/Global/VisualStudioCode.gitignore) it is helpful to allow committing `workspace settings` and `snippets` to the VC

I will create the necessary changes

**Comment by konstrybakov** [comment]
https://github.com/toptal/gitignore/pull/487 this is the PR

**Pull request merged**
