### PR TITLE
Update Python.gitignore

### PR DESCRIPTION
**Pull request by pofl**
# Pull Request

Thank you for contributing to @dvcs/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [ ] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [x] Template - Update existing `.gitignore` template

## Details

I __think__ these two should only match directories and not files. Having a .env file is quite common as in template `dotenv`. I am in a python project but don't want the .env file ignored.

### CODE REVIEW

**Comment by mingthegit** [comment]
I don't think `.env` files should be tracked. Also popular python projects all ignores `.env` file.

**Comment by pofl** [comment]
AFAIK .env has nothing to do with python. I agree 95% you should ignore the .env file if you use one. But it's still wrong to put this in the python template of all places. I had a case when I wanted the .env committed. And I was *surprised* by the fact that it was ignored. This is just wrong IMO.

**Comment by mingthegit** [comment]
My question is why should we have default template for 5% users? Template is always customizable.

**Comment by pofl** [comment]
It's a bad surprise and it has **nothing** to do with Python. According to your logic it would need to be added to *every* template. I strongly disagree with your opinion.

**Comment by gnechita-toptal** [comment]
@pofl Thank you for your suggestion. Could you please edit your PR, and just comment the two lines similar to what we are doing here for [Ruby](https://www.toptal.com/developers/gitignore/api/ruby)?

Maybe it's a good idea to keep the lines there as commented lines, and people could just uncomment if they need the `.env` and `.venv` files, instead of deleting them entirely.

WDYT?

**Comment by skeptycal** [comment]
### A bit of input into the conversation ...

There may be some confusion here on what items are python specific and should be included in the python `.gitignore` template. There are actually 2 similarly named, but very different, items that may be named any combination of [.v]env in the root of the repo. One definitely belongs here and one definitely does not.

### the .ENV File
- it is always a **file**
- or env, VENV, .VENV, venv, .venv ... or possibly some other names
- (those familiar with npm will recognize dotenv)
- contains general environment information, some of which may be private, but it is _often_ public config info and is tracked by git.
- This is the one that is **NOT** python specific, as @pofl mentioned, and does not belong here. I'm glad because that is a big argument about commenting it out and all. We don't have to concern ourselves with that here. Whew!

### the .ENV Folder
- is always a **folder**
- may be named env, .venv, or any variation of uppercase/lowercase ... it may also be named something user specific and we won't have to care.
- **the python virtual environment folder** (this one is always a **folder**) contains a copy (or symlinks) to a specific version of python/pip as well as a vendor folder for storing the correctly versioned dependencies. At a minimum, the dependencies pip, wheel, and setuptools are installed and versioned.
- None of this should ever by tracked by Git and it is rare to upload a copy of python and all dependencies with your repo unless it is a local company Git repo. Think of it like that huge _**node_modules**_ directory you see with common js and framework projects. You would never track or upload all that!

## The problem

>The problem here is that this _**folder**_ is often named `.env` or `.venv`, with or without the dot. This is an unfortunate coincidence since it is unrelated to the `.ENV` file, but **it is definitely a python specific** feature and **should definitely be included in any .gitignore file for a python project**.

## The proposed changes
... by @pofl are correct! The ***files*** should not be included, but the ***folders*** should be. Here is a shortened version of the rule that would account for most combinations:

    *[Ee][Nn][Vv]/

## The solution

The better solution may be to add your virtualenv to the .gitignore file directly. This way there is no confusion. If you vary the virtual environment names (which is a pain for scripting and automation! I use `.venv` for all of them.) you can automate adding your virtualenv to the .gitignore file during your automated boilerplate 'init' script setup thingie by using:

```sh
# after activating your virtualenv
# via bin/activate or conda activate

cd "$VIRTUAL_ENV"
echo "# repo specific python virtual environment:" >>.gitignore
echo "$VIRTUAL_ENV" >> .gitignore
```

---

## The part where I went overboard ... but maybe it helps someone

The python virtual environment folder is often located in the git repo root folder, but it does not have to be. It looks like this:

```sh
.
├── bin                # activation scripts, etc
├── include.           # vendor files
├── lib                # python interpreter of a specific version
└── pyvenv.cfg         # python version and virtual environment information
```

## An Option
For those interested in leaving this folder out of their repo folder completely, sharing environments between projects when the same python and dependency versions are used, or including everything in a [Docker image](https://docs.docker.com/engine/reference/commandline/image/):

Some of the common virtual environment managers ([pyenv](https://github.com/pyenv/pyenv), [pipenv](https://packaging.python.org/key_projects/#pipenv), [poetry](https://python-poetry.org/), but **NOT** pip), *can* create and manage a virtual environment folder outside of the repository. The `virtualenv` package is used in combination with `pip` by `pyenv` to achieve their results.

**`pip`** has complete version resolving as of [version 20.3](https://blog.python.org/2020/11/pip-20-3-release-new-resolver.html) and it is now the default. It supports Python 3.6+, Python 3.5 is deprecated (removal in v21.0) and Python2 is unsupported (the old resolver will remain the default)

## Poetry is beautiful

**`poetry`** and **`pipenv`** both have support version resolutions like **`NPM`** or **`Yarn`**, but `poetry` also supports:

- the latest pyproject.toml features for official package management requirements ([PEP 621 specification](https://www.python.org/dev/peps/pep-0621/))
- the basic project requirements ([PEP 518](https://www.python.org/dev/peps/pep-0518/) minimum requirements) like file formats ([Why TOML?](https://www.python.org/dev/peps/pep-0518/#overview-of-file-formats-considered)), build system requirements, and JSON Schema
- project version utilities ([PEP 440](https://www.python.org/dev/peps/pep-0440))
- project name ([PEP 503](https://www.python.org/dev/peps/pep-0503))


I find the `poetry` package manager to be the most complete and efficient lately. The [`pipenv` project](https://github.com/pypa/pipenv), by the infamous python developer and creative photographer [Kenneth Reitz](https://kennethreitz.org/), is the more ["official"](https://packaging.python.org/tutorials/managing-dependencies/) solution on `Pypi`, but there is not a "settled standard" and poetry is listed at the top of the ["other tools"](https://packaging.python.org/tutorials/managing-dependencies/#other-tools-for-application-dependency-management) list.

## Example

This example is on macOS. Linux is identical and Windows is similar enough. When logged in as 'USERNAME' and using **poetry**:

```sh
# the "virtualenvs.in-project" setting controls where the python
# and vendor dependencies reside
> poetry config --list

cache-dir = "/Users/USERNAME/Library/Caches/pypoetry"
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/USERNAME/Library/Caches/pypoetry/virtualenvs
```

Change the project default to unified user cache folder
*(notice there is no equals sign between the key and value)*
```sh
> poetry config virtualenvs.in-project false

> poetry config --list
cache-dir = "/Users/USERNAME/Library/Caches/pypoetry"
virtualenvs.create = true
virtualenvs.in-project = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/USERNAME/Library/Caches/pypoetry/virtualenvs
```


The creation of `virtualenv` directories can also be completely disabled if you want to manage them in some other way.

    > poetry config virtualenvs.create false

By the way, the rule for `lib/` on line 17 of commit [`89ac755`](https://github.com/toptal/gitignore/commit/89ac7551f360895b32b4f2884874620cb9e9c81f) applies to `python` `virtualenv` directories, but it also applies to many others and probably doesn't belong here.

If it is used in the `python` template, it should be `<virtual_environment_name>/lib/` to account for nested directory. If you want to automate this for some reason, perhaps when you 'init' a repo boilerplate, activate your virtualenv and use:

    cd $VIRTUAL_ENV
    echo "$VIRTUAL_ENV/lib" >> .gitignore

This will add the specific directory for your specific repo to the repository .gitignore file. Obviously, this should not be used in a global file.

Remember that this is a strange hacky solution, since if you are correctly adding the specific virtualenv to the .gitignore file ... everything in that folder will be ignored automatically.

**Comment by pofl** [comment]
@gnechita-toptal done.

**Comment by gobr** [comment]
thanks everyone for the input on this

**Pull request merged**
