### PR TITLE
Ignore directories from the Bazel IntelliJ plugin

### PR DESCRIPTION
**Pull request by jesseschalken**
# Pull Request

Thank you for contributing to @toptal/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [ ] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [x] Template - Update existing `.gitignore` template

## Details

These directories contain the generated project files from the Bazel IntelliJ plugin. See these links for info:

https://github.com/bazelbuild/intellij/blob/8c92239f41b20dcf88a22dcb3f44b5a9bdf46a95/.gitignore
https://github.com/bazelbuild/intellij/blob/8c92239f41b20dcf88a22dcb3f44b5a9bdf46a95/base/src/com/google/idea/blaze/base/sync/data/BlazeDataStorage.java#L36

### CODE REVIEW

**Review by deniskaber — CHANGES_REQUESTED** [review]
Hey @jesseschalken! Thank you for contributing to gitignore.io.

Your changes have to be moved to a `Bazel.patch` file. This way it won't be rewritten during sync with original github/gitignore repo.

**Comment by jesseschalken** [comment]
I didn't realise this repo had an upstream. I've opened a PR there: https://github.com/github/gitignore/pull/3869

**Comment by deniskaber** [comment]
Awesome! Thank you!

**Comment by jesseschalken** [comment]
This is fixed by https://github.com/toptal/gitignore/commit/41bf38845d24ebabec2821cb1d87a7ec814d8d8b which brings in my PR from upstream

**Pull request closed without merging**
