### PR TITLE
Fix Unreal Engine plugin binaries on subfolders

### PR DESCRIPTION
**Pull request by Maximetinu**
# Pull Request

Thank you for contributing to @toptal/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [ ] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [ x] Template - Update existing `.gitignore` template

## Details

This fix is to ignore binaries and intermediate files deeper in the Plugins/ hierarchy, as can be seen in the next screenshot:

image

### CODE REVIEW

**Review by deniskaber — CHANGES_REQUESTED** [review]
Hey @Maximetinu! Thank you for contributing to gitignore.io.

In order for this change to be preserved, you have to use .patch file with your change. This way it won't be rewritten during sync with original github/gitignore. 

Or you can also introduce this change to the source repository [here](https://github.com/github/gitignore/blob/master/UnrealEngine.gitignore). This way it will be automatically applied to this repo as well.

**Comment by filipechagas** [comment]
Hello @Maximetinu can you please check @deniskaber comment and adapt the PR?

**Comment by Maximetinu** [comment]
Hi @filipechagas

I forgot to mention that I did what you suggested, I opened a PR to the source repository https://github.com/github/gitignore/blob/master/UnrealEngine.gitignore so it is automatically applied to this repo as well.

This is the link to the PR: https://github.com/github/gitignore/pull/3858 it's still being reviewed, it's taking long..

**Comment by filipechagas** [comment]
Understood @Maximetinu
In the meantime, you can update this PR to add these lines to a `templates/UnrealEngine.patch` and we'd be happy to accept the contribution.

**Comment by Maximetinu** [comment]
Done! ✅ 

I have moved the new rules to the .patch file instead 🙂

**Review by filipechagas — APPROVED** [review]

**Comment by filipechagas** [comment]
Hey @Maximetinu I was about to merge the PR and notice there's an EOL problem. Can you please fix it?
I'm sorry I haven't noticed it before

**Comment by Maximetinu** [comment]
Done 🙂

**Pull request merged**
