### PR TITLE
Create Blender.gitignore

### PR DESCRIPTION
**Pull request by thiagosgarcia**
# Pull Request

Thank you for contributing to @toptal/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [X] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [ ] Template - Update existing `.gitignore` template

## Details

Create .gitignore template for Blender

### CODE REVIEW

**Comment by filipechagas** [comment]
Hi @thiagosgarcia ! Thanks for contributing.

Can you please update the PRs description with some more context? I'm a total stranger to Blender and would need more context to help to evaluate what should we put in the gitignore file.

**Comment by william-lohan** [comment]
I was about to make a similar PR. @thiagosgarcia the context is if you include you .blend files in a repo, like a game or Unity project, Blender saves autosave or backup files as .blend1

I have also seen the syntax `*.blend[0-9]*` I assume on rare occasion Blender keeps track of multiple autosave files I have also seen `__pycache__/` in Blender ignore files in case you are scripting with blender and have python scripts. But IDK if it'd be best practice to leave that for the python ignore template.

**Comment by filipechagas** [comment]
Thank you for the input, @william-lohan !
Since you were already on the verge of opening a PR, can you please go ahead and do that? In this case, I'd go with the `*.blend[0-9]*` format.

Regarding `__pycache__`, that's already included in https://github.com/toptal/gitignore/blob/master/templates/Python.gitignore#L2 so I think we're fine to leave it out of this one. WDYT?

**Comment by william-lohan** [comment]
Made #517 
I agree on leaving out `__pycache__`

**Comment by thiagosgarcia** [comment]
Hey! Thanks @william-lohan! I didn't know until a few days ago of the multiple autosave files on blender, so that was way better than my suggestion.
Sorry I didn't respond before @filipechagas, I was lured into somethings around here ended up leaving this PR aside.

I'll delete the branch since #517 was already merged. 
Thanks everyone!

**Pull request closed without merging**
