### PR TITLE
Added support for SvelteKit

### PR DESCRIPTION
**Pull request by MathRobin**
### New

- [x] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

## Details

I would like to add support of sveltekit framework, frontend component based framework, based on Svelte. https://kit.svelte.dev/
This template is based on skeleton project provided by the team who have created sveltekit

sample here https://github.com/sveltejs/kit-template-default/blob/main/.gitignore

### CODE REVIEW

**Review by filipechagas — CHANGES_REQUESTED** [review]
Hello 
Thanks for contributing!

Can you please capitalize the name of the file?

**Comment by MathRobin** [comment]
Done

**Review by filipechagas — CHANGES_REQUESTED** [review]
Sorry for the confusion, @MathRobin . The name must be `templates/Svelte.gitignore`

**Comment by MathRobin** [comment]
Changed! No problem!

**Review by yusufzmly — APPROVED** [review]
Hello @MathRobin , Thank you for taking the time to contribute to Gitignore!

**Pull request merged**
