### PR TITLE
add deno

### PR DESCRIPTION
**Pull request by f**
# Pull Request

Thank you for contributing to @toptal/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [x] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [ ] Template - Update existing `.gitignore` template

## Details

Added Deno .gitignore file with minimum reqs.

### CODE REVIEW

**Review by filipechagas — APPROVED** [review]

**Comment by filipechagas** [comment]
Thank you for contributing @f !

**Comment by filipechagas** [comment]
Thank you for contributing @f !

**Comment by martin-braun** [comment]
@f Thanks for adding Deno, but I have one concern. I don't work with VSCode, but I work with Neovim+Coc which supports VSCode extensions in NeoVim after some tweaks.

In order to not trip up my tsserver and all, I have to define these settings in my `coc-settings.json`:

```json
{
  "tsserver.enable": false,
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": false
}
```

This is the equivalent to `.vscode/settings.json`. This is also partially outlined in their doc: https://docs.deno.com/runtime/reference/vscode/#enabling-deno-in-a-vs-code-workspace

I noticed that the `tsserver` will get confused, too, so you have to disable it to make everything work right, at least in NeoVim.

Now your PR aggressively ignores `/.vscode/` which is imho wrong, because it forces everyone pulling the repo to clarify their settings, accordingly. Any reasoning behind your decision to exclude this folder without white-listing `settings.json`?

cc @filipechagas

**Comment by martin-braun** [comment]
Also, could you tell us a bit more about

```gitignore
*.orig
*.pyc
*.swp
```

`pyc` looks like Python garbage, `swp` looks like Vim garbage.

**Pull request merged**
