### PR TITLE
Added ignore for yarn v2

### PR DESCRIPTION
**Pull request by QuentinCaffeino**
# Pull Request

### New

- [x] Template - New `.gitignore` template

## Details

Added gitignore for the new yarn version as described here: https://yarnpkg.com/advanced/qa#which-files-should-be-gitignored

### CODE REVIEW

**Comment by sean0x42** [comment]
Perhaps a `.patch` should also be created for users that don't wish to use zero installs? It would only need to contain the following (plus an explanation of course):

```
.yarn/cache
.pnp.*
```

**Comment by QuentinCaffeino** [comment]
If I get it right patch will be automatically concatenated with gitignore file on the website. But it would give unexpected behavior cause users would expect zero-install to work. Should I add that patch with lines commented?

**Comment by sean0x42** [comment]
That's a good idea. Maybe the commented out lines could even go straight into the `yarn.gitignore`?

I'm not that familiar with this repository though, so that's just speculation. Would appreciate confirmation from someone more experienced first

**Comment by exKAZUu** [comment]
Hmmm, I think we should ignore `.yarn/cache` and `.pnp.*` by default for safety because "Zero-Install" requires us to add too many zip files in a git repo.
In my case, 32 deps yielded 755 zip files (37.8 MB). I imagine many developers want to avoid that.
How do you think?

**Comment by QuentinCaffeino** [comment]
Zero-install is one of two main features coming with yarnv2, so I would guess users would expect it to be on by default. They can always opt-out if they desire.

**Comment by sean0x42** [comment]
I think @QuentinCaffeino is right that Zero installs should be enabled by default, purely because that's the default behaviour of yarn V2.  Even though I think many developers will have the same thoughts as @exKAZUu (including myself). Zero installs appear to be a bit of a controversal addition.

**Comment by exKAZUu** [comment]
I've re-thought it again and recognized that the transfer size is same and only the differences are source (registry.yarnpkg.com v.s. github.com) and repo size. So, okay, I agree with both of them.

> That's a good idea. Maybe the commented out lines could even go straight into the yarn.gitignore?

I also agree with @sean0x42 suggestion. I would recommend to add 

```
# Uncomment the following lines if you're not using Zero-Installs
# .yarn/cache
# .pnp.*
```

or something. There are similar comments in this repo, e.g. https://github.com/toptal/gitignore/blob/master/templates/JetBrains.gitignore#L27-L38

**Pull request merged**
