### PR TITLE
Update CMake.patch

### PR DESCRIPTION
**Pull request by Maarrk**
# Pull Request

Thank you for contributing to @toptal/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [ ] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [ ] Template - Update existing `.gitignore` template
- [x] Patch - Template extending functionality of existing template

## Details

- Previously discussed in https://github.com/toptal/gitignore/pull/538
- Suggested to be moved to patch because it's stale in upstream https://github.com/github/gitignore/pull/3595
- Checked for more additions in [CMake's gitignore for CMake](https://gitlab.kitware.com/cmake/cmake/-/blob/release/.gitignore) itself, but seemed to be the only relevant file that's still missing

### CODE REVIEW

**Review by filipechagas — APPROVED** [review]
Thank you for accepting the change (you could've done in the same PR, but it's fine 😃 )

I guess this PR closes https://github.com/toptal/gitignore/pull/538

**Comment by Maarrk** [comment]
> (you could've done in the same PR, but it's fine 😃 )

@filipechagas Do you mean I could've added commits to #538, even though it was authored by someone else?

**Comment by filipechagas** [comment]
My bad. I got tricked by you commenting there into thinking you were the author of the previous one.

**Comment by filipechagas** [comment]
Thank you for contributing @Maarrk !

**Pull request merged**
