### PR TITLE
Fix fvm gitignore

### PR DESCRIPTION
**Pull request by tenhobi**
# Pull Request

Thank you for contributing to @toptal/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [ ] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [x] Template - Update existing `.gitignore` template

## Details

Fix of FVM gitignore based on its docs https://fvm.app/docs/getting_started/configuration#project

### CODE REVIEW

**Comment by yusufzmly** [comment]
Hello @tenhobi, thanks for your contribution.

I saw that it is recommended to add `.fvm/flutter_sdk` to gitignore here https://fvm.app/docs/getting_started/configuration.
But i also saw that `.fvm` is added to gitignore here https://github.com/fluttertools/fvm/blob/main/.gitignore . Could you please tell us why you are removing the `.fvm` from .gitignore ?

**Comment by tenhobi** [comment]
@yusufzmly hi, the reason why they have in the docs to ignore `.fvm/flutter_sdk` only is because the `.fvm/` directory contains at least file `.fvm/fvm_config.json`, where the config about version to be downloaded as `.fvm/flutter_sdk` is stored.

Ergo by ignoring the whole directory, config file would be also ignored.

cc @leoafarias

**Comment by yusufzmly** [comment]
> Ergo by ignoring the whole directory, config file would be also ignored.

@tenhobi thanks for the explanation 👍

**Review by yusufzmly — APPROVED** [review]

**Review by alexmcode — APPROVED** [review]
Thanks for the contribution @tenhobi! Looks good 👍

**Pull request merged**
