### PR TITLE
feat(python): ignore .pdm.toml

### PR DESCRIPTION
**Pull request by jjangga0214**
# Pull Request

Thank you for contributing to @toptal/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### Update

- [x] Template - Update existing `.gitignore` template

## Details
[`pdm`](https://github.com/pdm-project/pdm) is one of the promising package managers in python ecosystem.
It generates `.pdm.toml`, which must be ignored.

### CODE REVIEW

**Review by deniskaber — CHANGES_REQUESTED** [review]
Hey @jjangga0214 ! Thank you for contributing to gitignore.io.

Your changes have to be moved to a `Python.patch` file. This way it won't be rewritten during sync with original github/gitignore repo.

**Comment by jjangga0214** [comment]
@deniskaber Thanks. 
I allowed edits by maintainers. 
Would you ping someone?

**Comment by jjangga0214** [comment]
@deniskaber I've resolved conflict anyway. 
I hope you or another maintainer move this to `Python.patch` file. 
Or please let me know how.
Thanks.

**Comment by filipechagas** [comment]
Hello @jjangga0214 
Can you please fix the PR so it make the desired changes in a file called `templates/Python.patch` instead of `templates/Python.gitignore`?

**Comment by astrojuanlu** [comment]
I opened https://github.com/github/gitignore/pull/3976, which I believe would supersede this one.

**Comment by yusufzmly** [comment]
Thank you for taking the time to contribute, @astrojuanlu and @jjangga0214 !

We are closing this pr because it has been already done https://github.com/github/gitignore/pull/3976 and this pr has no activity since 30 days.

**Pull request closed without merging**
