### PR TITLE
Update Godot

### PR DESCRIPTION
**Pull request by IceflowRE**
# Pull Request

Thank you for contributing to @toptal/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [ ] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [x] Template - Update existing `.gitignore` template

## Details

Add `.godot` directory which is used instead of `.import` in Godot 4.

### CODE REVIEW

**Comment by filipechagas** [comment]
Thank you for contributing, @IceflowRE !

It seems like this change is already present in [the upstream](https://github.com/github/gitignore/blob/main/Godot.gitignore), and was already picked up by our CI.

Your PR is also removing `templates/NWjs.gitignore` which is not mentioned in the PR description. Was that intentional? If so, could you please share the reasoning?

**Review by filipechagas — CHANGES_REQUESTED** [review]
Thank you for contributing, @IceflowRE !

It seems like this change is already present in [the upstream](https://github.com/github/gitignore/blob/main/Godot.gitignore), and was already picked up by our CI.

Your PR is also removing `templates/NWjs.gitignore` which is not mentioned in the PR description. Was that intentional? If so, could you please share the reasoning?

**Comment by IceflowRE** [comment]
> 
> Your PR is also removing `templates/NWjs.gitignore` which is not mentioned in the PR description. Was that intentional? If so, could you please share the reasoning?

Good catch i thought i didn't pushed it, but anyway the issue is that, on Windows the NWJS file gets replaced by `Nwjs.gitignore` or `NWjs.gitignore`, always the opposite gets marked as deleted in git to what is currently in the filesystem, seems to be an issue with the casing.

**Comment by filipechagas** [comment]
Wow, very true! I'd never noticed we had a duplicated version of this file.
Thank you for pointing it out! I just removed it from the repo: https://github.com/toptal/gitignore/commit/878647ceb393953e6e4de2e26ec9817682cd78a3

**Pull request closed without merging**
