### PR TITLE
Create replit.gitignore

### PR DESCRIPTION
**Pull request by stellasphere**
# Pull Request

Thank you for contributing to @toptal/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [x] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [ ] Template - Update existing `.gitignore` template

## Details

Create a `.gitignore` template for the online IDE [Replit](https://replit.com/)

### CODE REVIEW

**Comment by stellasphere** [comment]
@filipechagas could you take a look at this?

**Review by konstrybakov — DISMISSED** [review]

**Comment by konstrybakov** [comment]
@stellasphere, thank you for taking the time to contribute! I am not too familiar with `repl.it` IDE, but having a quick look at https://docs.replit.com/programming-ide/configuring-repl it seems that these are important config files. 

So for example without having the `.nix` file, `repl` wouldn't know which technologies you want available in your environment, isn't it so? 

```nix
{ pkgs }: {
	deps = [
		pkgs.nodejs-16_x
        pkgs.nodePackages.typescript-language-server
        pkgs.yarn
        pkgs.replitPackages.jest
	];
}
```

Can you elaborate please, why do you want to `.gitignore` them? Could it be that it is just related to your special use-case and would not be applicable to the everyone?

**Comment by stellasphere** [comment]
Hi, thanks for the reply. The files configure the language that the "repl" is run in. Even within Repl.it the files are recreated when importing based on the language makeup and if Replit config files are already present, they are overwritten by the newly generated ones anyways.

**Review by konstrybakov — APPROVED** [review]
Hey @stellasphere, thank you for the contribution, and for the explanation!

**Review by alexmcode — APPROVED** [review]

**Pull request merged**
