### PR TITLE
Create vRealizeOrchestrator.gitignore

### PR DESCRIPTION
**Pull request by imtrinity94**
# Pull Request

Thank you for contributing to @toptal/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [x] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [ ] Template - Update existing `.gitignore` template

## Details

vRealize Orchestrator is a Cloud Automation IDE which has git capabilities inbuilt. But doesn't provide gitignore template out of the box. Hence, adding it here to the biggest collection of gitignore.
Article supporting it: https://cloudblogger.co.in/2022/05/16/dont-ignore-gitignore-in-vro-8-x/
What is vRO: https://www.vmware.com/in/products/vrealize-orchestrator.html
vRO Community Discussion: https://communities.vmware.com/t5/vRealize-Orchestrator/vRO-git-repo-exclude-configuration-elements-and-resource/m-p/2901690#M25733

### CODE REVIEW

**Review by yusufzmly — APPROVED** [review]
Hello @imtrinity94 , Thank you for taking the time to contribute to Gitignore!

**Comment by imtrinity94** [comment]
image

I need to know when can I search for vRealize Orchestrator on the mail gitignore.io page?

**Comment by filipechagas** [comment]
@imtrinity94 You should already be able to.
https://www.toptal.com/developers/gitignore/api/vrealizeorchestrator

**Comment by imtrinity94** [comment]
My observation says it took few days before the gitignore.io homepage could show it.

**Pull request merged**
