### PR TITLE
Add React/Gatsby ignore to Node template.

### PR DESCRIPTION
**Pull request by eclectic-coding**
# Pull Request

Thank you for contributing to @dvcs/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate checkbox for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [ ] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [X ] Patch - Template extending functionality of existing template

### Update

- [ ] Template - Update existing `.gitignore` template

## Details
Added section to Node template to include ReactJS and Gatsby public folder.

### CODE REVIEW

**Comment by applefreak** [comment]
I don't think this is a good idea... a lot of non Gatsby projects uses `public/` folder.

**Comment by gabrielizaias** [comment]
I just got caught by this as well. Ignoring `public/` has side effects on code bases that are not js-only.

**Comment by eclectic-coding** [comment]
Can't you use a different command switch?
`gi node` generates a gitignore for node based applications.

**Comment by gabrielizaias** [comment]
I see your point @eclectic-coding. I would argue that many projects don't use only 1 parameter.

Take `gi laravel,node` for example. It has a conflict where some contents of the `public/` folder are ignored by the `laravel` parameter, but then the entire folder is ignored by the `node` parameter, given this change.

The change in #251 seems reasonable to me, the entry is commented out with an explanation to un-comment it. Maybe an even better solution would be `gi gatsby`?

What do you think?

**Comment by eclectic-coding** [comment]
@gabrielizaias I think that is a great idea ... Gatsby is a viable growing framework and this might be necessary since it is a React derivative but at the same time different.

**Pull request merged**
