### PR TITLE
Update CMake.gitignore

### PR DESCRIPTION
**Pull request by rvodden**
# Pull Request

Thank you for contributing to @toptal/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [ ] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [X] Template - Update existing `.gitignore` template

## Details

CMake 3.19 introduced a feature which allows project maintainers to distribute CMake settings with their code. In addition, there is a facility for users to maintain a local set of CMake settings for convenience.

[CMake Profiles Documentation](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html)

>CMakePresets.json may be checked into a version control system, and CMakeUserPresets.json should NOT be checked in. For example, if a project is using Git, CMakePresets.json may be tracked, and CMakeUserPresets.json should be added to the .gitignore.

### CODE REVIEW

**Comment by rvodden** [comment]
@yusufzmly anything I need to do to get this merged? :-)

**Review by alexmcode — APPROVED** [review]
Hey @rvodden it looks good! Thank you for the contribution and sorry for the long wait time. Let's wait for one more review and it should be good to merge 👍

**Comment by Maarrk** [comment]
Just dropping a comment from a user (me) that this seems fairly clear for a potential reviewew and I'd really like it, thanks in advance 👍

**Review by filipechagas — CHANGES_REQUESTED** [review]
Hey @rvodden thank you for contributing.

The change looks good! This file, however, is mirrored from https://github.com/github/gitignore/blob/main/CMake.gitignore and would be overwritten by CI if we merge as is.
In this case, you'll want to either open a PR in the upstream repository, or move this change [to a patch file](https://github.com/toptal/gitignore#files).

**Comment by Maarrk** [comment]
The PR is already in the upstream https://github.com/github/gitignore/pull/3595, from 3 years ago, contributed by someone from Kitware (creators of CMake).

I dropped the same comment there to hopefully move it up some "recent" list

**Comment by filipechagas** [comment]
Got it! In that case, a patch file will come in handy. If you care to make the change we'll be happy to merge it.

**Comment by filipechagas** [comment]
Surpersed by https://github.com/toptal/gitignore/pull/557

**Pull request closed without merging**
