### PR TITLE
Add missing Nuxt 3's generated dirs

### PR DESCRIPTION
**Pull request by luvejo**
## Update

- [x] Template - Update existing `.gitignore` template

## Description
I updated the Nuxt section to include the new Nuxt 3 generated folders.

## References
- Official [.gitignore](https://github.com/nuxt/nuxt/blob/main/.gitignore#L22-L24) file.
- Nuxt Team's recommended .gitignore [entries](https://nuxt.com/docs/guide/directory-structure/gitignore#git-ignore-file).

### CODE REVIEW

**Review by filipechagas — CHANGES_REQUESTED** [review]
Hi @luvejo 
Thank you for contributing!

However, this file is mirrored from https://github.com/github/gitignore/blob/main/Node.gitignore and will be overwritten by our Ci. You can contribute directly to the upstream or use a `patch` [file](https://github.com/toptal/gitignore#files) instead.

I would also recommend creating a NustJS-specific ignore. WDYT?

**Comment by luvejo** [comment]
Thank you for such a quick response!

I made a PR to the upstream repo, but it looks they haven't approved anything in a while. So I moved the changes to a separate NuxtJS file, as you suggested.

**Review by filipechagas — APPROVED** [review]
Thank you for updating the PR!

Do you think we should add `node_modules` here too, as [the documentation](https://nuxt.com/docs/guide/directory-structure/gitignore) suggests? Though we already have it the Node.gitignore so I guess it's ok to leave it out.

Can you please fix the EOL issue? Then we can merge and publish it.

**Comment by yusufzmly** [comment]
Thank you for contributing @luvejo !

**Pull request merged**
